<div id="view-content">
	<dl>
		<dt>Zend Db Adapter is</dt>
		<dd><?php echo $this->ZendDbAdapter ?></dd>
		<dt>Zend Db Table has default metadata cache</dt>
		<dd><?php echo $this->ZendDbTableHasDefaultMetadataCache ?></dd>
		<dt>Zend Locale has cache</dt>
		<dd><?php echo $this->ZendLocaleHasCache ?></dd>
		<dt>Zend Http UserAgent Device has feature MP3</dt>
		<dd><?php echo $this->ZendHttpUserAgentDeviceHasFeatureMp3 ?></dd>
	</dl>
</div>